services:
  nginx:
    container_name: warpzone_nginx
    depends_on:
      - api-gaming-manager
    image: nginx:alpine
    networks:
      - warpzone_network
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd:ro # basic auth
      - ./docker/nginx/default.staging.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl:ro
      - ./dist:/usr/share/nginx/html:ro

  api-gaming-manager:
    container_name: warpzone_api_gaming_manager
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.staging
      args:
        EXPOSE_PORT: 3000
        PROJECT_NAME: api-gaming-manager
    image: api-gaming-manager
    depends_on:
      - database
    networks:
      - warpzone_network
    restart: on-failure
    expose:
      - '3000' # expose only in the warpzone_network
    volumes:
      - ./dist/:/var/www/dist:Z
    environment:
      APP_HOST: 0.0.0.0
      APP_PORT: 3000
      DATABASE_NAME: $DATABASE_NAME
      DATABASE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      ENVIRONMENT: staging
      MAIL_DRIVER: $MAIL_DRIVER
      MAIL_ENCRYPTION: $MAIL_ENCRYPTION
      MAIL_HOST: $MAIL_HOST
      MAIL_PORT: $MAIL_PORT
      MAIL_USERNAME: $MAIL_USERNAME
      MAIL_PASSWORD: $MAIL_PASSWORD
      SECRET_COOKIE: $SECRET_COOKIE
      SECRET_JWT: $SECRET_JWT

  database:
    container_name: warpzone_database
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    image: mysql:8.4.0-oraclelinux8
    networks:
      - warpzone_network
    ports:
      - 3306:3306
    restart: on-failure
    volumes:
      - ./docker/mysql/data:/var/lib/mysql:Z
    environment:
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
