# Redirect HTTP traffic to HTTPS
server {
    listen 80;
    server_name wtwz.it www.wtwz.it;

    location / {
        return 301 https://$host$request_uri;
    }
}

# Main HTTPS server
server {
    listen 443 ssl;
    server_name wtwz.it www.wtwz.it;

    # SSL certificate
    ssl_certificate     /etc/nginx/ssl/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/privkey.pem;

    # Enable gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml;
    gzip_min_length 256;
    gzip_vary on;
    gzip_proxied any;

    # Deny access to hidden files like .htaccess, .env, etc.
    location ~ /\. {
        deny all;
    }

    # Redirect /admin to /admin/
    location = /admin {
        return 301 /admin/;
    }

    # Api: Gaming Manager
    location /api/ {
        # proxy_pass needs the service name instead of the container name
        proxy_pass http://api-gaming-manager:3000/; 
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Game: Hoopify City
    # Served at /
    location / {
        root /usr/share/nginx/html/game-hoopify-city;
        index index.html;
        try_files $uri $uri/ /index.html;

        # Basic Auth
        auth_basic "Restricted Area";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }

    # Static files cache
    location /assets/ {
        root /usr/share/nginx/html/game-hoopify-city;
        expires max;
        access_log off;
        add_header Cache-Control "public, immutable";
    }

    # Web: Admin
    # Served at /admin/
    # TODO handle navigation like /admin/login or /admin/profile
    location ^~ /admin/ {
        alias /usr/share/nginx/html/web-admin/;
        index index.html;
        try_files $uri $uri/ /web-admin/index.html;
    }

    # Static files cache
    location /admin/assets/ {
        alias /usr/share/nginx/html/web-admin/assets/;
        expires max;
        access_log off;
        add_header Cache-Control "public, immutable";
    }
}
