server {
  listen 80;
  listen 443 ssl;
  server_name localhost;

  ssl_certificate     /etc/nginx/ssl/localhost.pem;
  ssl_certificate_key /etc/nginx/ssl/localhost-key.pem;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers HIGH:!aNULL:!MD5;

  # Api: Gaming Manager
  location /api/ {
    rewrite ^/api/(.*)$ /$1 break;
    proxy_pass http://warpzone_api_gaming_manager:3000/;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # Web: Admin
  location /admin/ {
    proxy_pass http://warpzone_web_admin:4200/admin/;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_redirect off;
  }

  # Game: Hoopify City
  location / {
    proxy_pass http://warpzone_game_hoopify_city:5200/;

    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
